[package]
name = "podrez"
version = "0.1.0"
edition = "2021"
authors = ["human9000 human9000.2021@gmail.com"]
license-file = "LICENSE"

[dependencies]
awedio = "0.4.1"
ctrlc = "3.4.5"
rand = "0.8.5"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
ureq = "2.10.1"
rodio = "0.17.3"

[dependencies.windows]
version = "0.58.0"
features = [
    "Win32_Media_Audio",
    "Win32_System_Com",
    "Win32_Media_Audio_Endpoints",
    "Win32_Foundation",
    "Win32_UI",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Media_Audio"
]

[profile.dev]
panic = "unwind"

[profile.release]
lto = true
opt-level = "z"
debug = 0
codegen-units = 1
strip = true

[profile.release.package."*"]
opt-level = "z"
strip = true
