[package]
name = "podrez"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rodio = "0.19.0"
rusty_audio = "1.4.1"

[profile.release]
lto = true
opt-level = "z"
debug = 0
codegen-units = 1
strip = true
